### ISSUE TITLE
[Bug] Logout is hard to read when using vertical layout and dark sidebar

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/theme-tabler#99]
# Bug report

### What I did

I am using `'layout' => 'vertical_dark',`

### What I expected to happen

All labels should be visible and easy to read

### What happened

The logout link, dark red on dark background is not easy to read

![image](https://github.com/Laravel-Backpack/theme-tabler/assets/1268699/caa53d4f-a6e4-4a5f-a5a9-9c2a02a9cc95)

### What I've already tried to fix it

Actually nothing, if any I'll update this

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
php artisan backpack:version
### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 19 2022 10:13:52) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.14.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.0.0
backpack/crud: 6.0.1
backpack/generators: v4.0.0
backpack/pro: 2.0.5
backpack/theme-tabler: 1.0.1
```

**Comment by promatik** [comment]
Hi @realtebo!
Thank you for your report, I just pushed a PR with a bunch of fixes to tabler theme, one of them is exactly this one.

"Danger" text color is now slightly lighter, in order for it to pass the WCAG ([Web Content Accessibility Guidelines](https://www.w3.org/WAI/WCAG2AA-Conformance)) AA test 👌

This fix is part of; https://github.com/Laravel-Backpack/theme-tabler/pull/102

**Comment by realtebo** [comment]
how can I update my app?

**Comment by tabacitu** [comment]
@realtebo we haven't tagged that release yet. But we will today. At the end of the day, you'll be able to do `composer update` and get all the latest fixes.

**Comment by realtebo** [comment]
Sorry, but the problem is still here

![image](https://github.com/Laravel-Backpack/theme-tabler/assets/1268699/2ff24ac3-6891-4bbc-9f58-b39c997e00ea)

```
### PHP VERSION:
PHP 8.2.8 (cli) (built: Jul  4 2023 15:53:15) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.17.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.1.1
backpack/crud: 6.1.7
backpack/generators: v4.0.2
backpack/pro: 2.0.10
backpack/theme-tabler: 1.0.8
```

Is there somthing is expected I republish?
